In [1]:
import torch
device='cuda' if torch.cuda.is_available() else 'cpu'

In [2]:
import time
import numpy as np

In [3]:
%%time
start_time=time.time()
zeros=torch.zeros(100,100,100,100)
end=time.time()

tt=end-start_time
print(f"{tt:.8f}")

0.31452322
CPU times: total: 297 ms
Wall time: 315 ms


In [4]:
randint=torch.randint(-100,100,(5,))

In [5]:
randint

tensor([ 73, -58,  -3,  13, -28])

In [6]:
tensor=torch.tensor([[0.1,0.2],[0.1,0.3],[0.1,-0.3]])
tensor

tensor([[ 0.1000,  0.2000],
        [ 0.1000,  0.3000],
        [ 0.1000, -0.3000]])

In [7]:
zeros=torch.zeros(5,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [8]:
device

'cuda'

In [9]:
start_time=time.time()

zeros=torch.zeros(30,50)
end=time.time()

tt=end-start_time
print(f"{tt:.4f}")


0.0000


In [50]:
torch_rand1=torch.rand(100,100,100,100).to(device)
torch_rand2=torch.rand(100,100,100,100).to(device)
np_rand1=torch.rand(100,100,100,100)
np_rand2=torch.rand(100,100,100,100)

start_time=time.time()
rand=(torch_rand1@torch_rand2)
end=time.time()
tt=end-start_time
print(f"{tt:.10f}")


start_time=time.time()
rand=np.multiply(np_rand1,np_rand2)
end=time.time()
tt=end-start_time
print(f"{tt:.10f}")

0.0039989948
0.1159999371


In [11]:
probebilities=torch.tensor([0.1,0.9])
samples=torch.multinomial(probebilities,num_samples=10,replacement=True)
samples

tensor([1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

In [12]:
tensor=torch.tensor([1,2,3,4])
out=torch.cat((tensor,torch.tensor([5])),dim=0)
out

tensor([1, 2, 3, 4, 5])

In [13]:
torch.tril(torch.ones(5,5))

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [14]:
torch.triu(torch.ones(5,5))

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [15]:
out=torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5))==0,float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [16]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [17]:
input=torch.zeros(2,3,4)
out=input.transpose(0,2)
out.shape
# print(input)
# print(out)

torch.Size([4, 3, 2])

In [18]:
tensor1=torch.tensor([1,2,3])
tensor2=torch.tensor([4,5,6])
tensor3=torch.tensor([7,8,9])
out=torch.stack([tensor1,tensor2,tensor3])
out

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [3]:
import torch.nn as nn
import torch.nn.functional as F

In [20]:
sample=torch.tensor([10.0,10.0,10.0])

In [27]:
linear=nn.Linear(3,3,bias=False)
print(linear(sample))

tensor([-2.0868, -6.8134, -4.7768], grad_fn=<SqueezeBackward4>)


In [31]:
tensor1=torch.tensor([1.0,2.0,3.0])

softmax_out=F.softmax(tensor1,dim=0)

In [32]:
print(softmax_out)

tensor([0.0900, 0.2447, 0.6652])


In [39]:
vocab_size=10000
embedding_dim=100

embedding=nn.Embedding(vocab_size,embedding_dim)

input_indices=torch.LongTensor([1,5,3,2])

embedded_output=embedding(input_indices)

print(embedded_output.shape)

torch.Size([4, 100])


In [42]:
a=torch.tensor([[1,2],[3,4],[5,6]])
b=torch.tensor([[7,8,9],[10,11,12]])
# print(a@b)
print(torch.matmul(a,b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [49]:
int_64=torch.randint(1,(3,2)).float()
float_32=torch.rand(2,3)
# print(int_64.dtype,float_32.dtype)

result=torch.matmul(int_64,float_32)
# print(result)
print(int_64@float_32)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [9]:
a=torch.rand(2,3,5)
x,y,z=a.shape
b=a.view(x,y,z)
print(a)
print(b)

tensor([[[0.0292, 0.3249, 0.5945, 0.8525, 0.3974],
         [0.8075, 0.6707, 0.6528, 0.3232, 0.7994],
         [0.2946, 0.4835, 0.5783, 0.7165, 0.3240]],

        [[0.6583, 0.1177, 0.7685, 0.8802, 0.5739],
         [0.1452, 0.4217, 0.8252, 0.2856, 0.9214],
         [0.2620, 0.8311, 0.4505, 0.1416, 0.0228]]])
tensor([[[0.0292, 0.3249, 0.5945, 0.8525, 0.3974],
         [0.8075, 0.6707, 0.6528, 0.3232, 0.7994],
         [0.2946, 0.4835, 0.5783, 0.7165, 0.3240]],

        [[0.6583, 0.1177, 0.7685, 0.8802, 0.5739],
         [0.1452, 0.4217, 0.8252, 0.2856, 0.9214],
         [0.2620, 0.8311, 0.4505, 0.1416, 0.0228]]])
